version: '3.1'

services:
  lb:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  web:
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    environment:
      VIRTUAL_HOST: static.sara.local
